apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    deployment: first-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 80
    #   targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: first-app
      tier: backend
  template:
    metadata:
      labels:
        deployment: first-app
        tier: backend
    spec:
      containers:
        - name: first-containers
          image: academind/kub-first-app:2
